language: ruby
notifications:
  email: false
  slack:
    secure: EGzPzq5N5BpH56Ms396M/Z0GMjhy7lYMWwD5pwOfMFSJvdCc+O9Rj/E6lrEyJ5d394tuU+nXNYATIj+l+loTfS7aH7pwP1cK9AfP7ba8BDVyn2T30WLJ3uv/lJAXQCDL3se8OSUcos/Sq3Gy+jLA3lwIREns6mUh8Tq31ci04+kY4Tpfq8Nps5J9PB8buNOdImO5m3PQ0903E/FnPaBS1Q4Q+aE/6JqMuScSkWjbKkHih6aPUllOrzje+66//dLfixVNGPwA8Zy2Oc7v6ZbsDRpOBGQu/v4eM8f4ntJ28UfkL8H/fZ3PABp0fTmDPBI7+XEWkD2PddvNc7KXzZl4RGMYyMm4nBeOpcXWNHuv38eUGh+nBNpZVYGcgDbbCTfr8TWN/fwn3bBfqy+191md77YHEB3GsEeJNcvDJNT7ECnv+zUBxFY8r6kEeOT2hH2qHGpicLOEtwZWffYRBMtC3kZjH4y8iNydvranUNca/4kwBsYGSqvAA20fgOLlw23hhi7vwBdJGE3EP6RKwEAKXPdMqe4HPQII4IW/DgT42ScLXOlit3qFRhwemDHb2f4vYtS+FSLALIY2ng1gSHpWfkCAo3cy5wOhvnCS7xHHCbVWQP/3Acyh8C6XmZJyjsq/yNO0SkET0fv7QPW93eZsdorlL5wrap/zWCttF4C1s+k=
rvm:
- 2.3.1
cache:
- bundler
- apt
sudo: required
addons:
  postgresql: '9.5'
before_script:
- psql -c 'create database photo_market_test;' -U postgres
- bundle exec rails db:migrate
script:
- bundle exec rails ci:tests

deploy:
  provider: heroku
  api_key:
    secure: G0Vx+LWtzXCUQphcjNMqXteUZngKr+tptMdxn8IlPKMyU0ilPY8vo9y4qwHt2CJDWtMt/oQKhn2Zop6poKgawOwxDWucsHHENZZyCuzgEe0SXJ/6heBZ+FAatv9Ah0dHD6BPagqLGeog/9s54yEx906a6JbVhjMIpz++gufARx24A3JOAsBDSbF4yvLHnGeUSH2jEhSXRcFJnEh7aFw6cH79Pp1mO9Ocwf/hfzYmcAQz+jbMCRCaPU0rY8EM5QtD7utHiqwcUxZVP5vJQ1cUDbGBIe7AVFgZTOoj+ZJjbgbllv7PLIAhWDU4VIf/UVzXhQAUpX8Sh6rY+katwwdD9zxMPTJvQGWqWbDSKNtC3dlDjNfKBOr/J3H6R4tR7kclOymwUL2oxiAOW6o6TouW5/RzbzUSqJSKbALebFhttXjGRvaWusGtH0zdoI08EGxtrWr+N5qrHXRaw4gteGcc3EBb4eYzCa5PhpEryblAtHjxM901GOG8TL0aSxhgFc+TBcAlLvFBP/EOFqTIEFATGmri3cIEogGYeuF+5+HJFUAoALFYZGwZGj5S/BXA2uyGitm6RQm4JZFBW4iLhFTaW7avG6mZUEz9XjySaSFlPlpMQI+TJ2eOuroRTXyjel6GZ3bWNNK489QZM84CmT214dRlxkOsv47Ix0DrQ0djvNw=
  app:
    develop: photo-market-inc
